services:
  ml-ids:
    build:
      context: .
      dockerfile: src/inference_server/Dockerfile
    container_name: ml-ids
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "python3", "/app/validate_interface.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      # MLflow configuration (required)
      - MLFLOW_TRACKING_URI=http://xxx.xxx.xxx.xxx:5050
      - MLFLOW_S3_ENDPOINT_URL=http://xxx.xxx.xxx.xxx:9000

      # AWS credentials for S3 (required)
      - AWS_ACCESS_KEY_ID=xxxx
      - AWS_SECRET_ACCESS_KEY=xxxx
      
      # Control whether CICFlowMeter is started
      - START_CICFLOWMETER=true
      
      # Model configuration
      - MLFLOW_MODEL_NAME=models:/ML_IDS_Model_v1/latest
      
      # CICFlowMeter configuration
      - CIC_INTERFACE=eth0
      
      # Optional configuration
      - LOG_DIR=/app/logs
    volumes:
      # Mount logs directory for persistence
      - /var/log/ml-ids:/app/logs
    restart: unless-stopped

# To use this file:
# 1. Update environment variables with your actual values
# 2. Run: docker-compose up -d
# 3. Check logs: docker-compose logs -f ml-ids
