services:
  ml-ids:
    build:
      context: .
      dockerfile: src/inference_server/Dockerfile
    container_name: ml-ids
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      # MLflow configuration (required)
      - MLFLOW_TRACKING_URI=http://your-mlflow-server:5000
      - MLFLOW_S3_ENDPOINT_URL=http://your-s3-endpoint:9000
      
      # AWS credentials for S3 (required)
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      
      # CICFlowMeter configuration
      - CIC_INTERFACE=eth6
      
      # Optional configuration
      - LOG_DIR=/app/logs
    volumes:
      # Mount logs directory for persistence
      - /var/log/ml-ids:/app/logs
    restart: unless-stopped

# To use this file:
# 1. Update environment variables with your actual values
# 2. Run: docker-compose up -d
# 3. Check logs: docker-compose logs -f ml-ids
