# SonarQube Project Configuration
sonar.projectKey=ml-ids
sonar.projectName=ML-IDS
sonar.projectVersion=1.0
sonar.login=admin
sonar.password=patilla1

# Path to source and test directories
sonar.sources=src
sonar.tests=tests

# Language and encoding
sonar.language=py
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8

# Coverage Report (pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/__pycache__/**, **/.venv/**, **/tests/**
sonar.test.inclusions=tests/test_*.py
