#!/bin/bash
# Test inference_server /predict endpoint with a full feature set

curl -X POST http://localhost:8000/predict \
  -H "Content-Type: application/json" \
  -d '{
    "Flow Duration": 1000,
    "Total Fwd Packet": 2,
    "Total Bwd packets": 2,
    "Total Length of Fwd Packet": 100.0,
    "Total Length of Bwd Packet": 100.0,
    "Fwd Packet Length Max": 50.0,
    "Fwd Packet Length Min": 0.0,
    "Fwd Packet Length Mean": 25.0,
    "Fwd Packet Length Std": 10.0,
    "Bwd Packet Length Max": 50.0,
    "Bwd Packet Length Min": 0.0,
    "Bwd Packet Length Mean": 25.0,
    "Bwd Packet Length Std": 10.0,
    "Flow Bytes/s": 1000.0,
    "Flow Packets/s": 2.0,
    "Flow IAT Mean": 500.0,
    "Flow IAT Std": 100.0,
    "Flow IAT Max": 1000.0,
    "Flow IAT Min": 0.0,
    "Fwd IAT Total": 1000.0,
    "Fwd IAT Mean": 500.0,
    "Fwd IAT Std": 100.0,
    "Fwd IAT Max": 1000.0,
    "Fwd IAT Min": 0.0,
    "Bwd IAT Total": 1000.0,
    "Bwd IAT Mean": 500.0,
    "Bwd IAT Std": 100.0,
    "Bwd IAT Max": 1000.0,
    "Bwd IAT Min": 0.0,
    "Fwd PSH Flags": 0,
    "Bwd PSH Flags": 0,
    "Fwd URG Flags": 0,
    "Bwd URG Flags": 0,
    "Fwd Header Length": 20,
    "Bwd Header Length": 20,
    "Fwd Packets/s": 2.0,
    "Bwd Packets/s": 2.0,
    "Packet Length Min": 0.0,
    "Packet Length Max": 50.0,
    "Packet Length Mean": 25.0,
    "Packet Length Std": 10.0,
    "Packet Length Variance": 5.0,
    "FIN Flag Count": 0,
    "SYN Flag Count": 0,
    "RST Flag Count": 0,
    "PSH Flag Count": 0,
    "ACK Flag Count": 0,
    "URG Flag Count": 0,
    "CWR Flag Count": 0,
    "ECE Flag Count": 0,
    "Down/Up Ratio": 1.0,
    "Average Packet Size": 25.0,
    "Fwd Segment Size Avg": 20.0,
    "Bwd Segment Size Avg": 20.0,
    "Fwd Bytes/Bulk Avg": 0.0,
    "Fwd Packet/Bulk Avg": 0.0,
    "Fwd Bulk Rate Avg": 0.0,
    "Bwd Bytes/Bulk Avg": 0.0,
    "Bwd Packet/Bulk Avg": 0.0,
    "Bwd Bulk Rate Avg": 0.0,
    "Subflow Fwd Packets": 1,
    "Subflow Fwd Bytes": 100,
    "Subflow Bwd Packets": 1,
    "Subflow Bwd Bytes": 100,
    "FWD Init Win Bytes": 0,
    "Bwd Init Win Bytes": 0,
    "Fwd Act Data Pkts": 0,
    "Fwd Seg Size Min": 0,
    "Active Mean": 0.0,
    "Active Std": 0.0,
    "Active Max": 0.0,
    "Active Min": 0.0,
    "Idle Mean": 0.0,
    "Idle Std": 0.0,
    "Idle Max": 0.0,
    "Idle Min": 0.0
  }'
