# Network interface to capture traffic from
interface = "eth0"

# Directory to store PCAP files before uploading to MinIO
pcap_dir = "/data/pcaps"

# Duration in seconds before rotating to a new PCAP file
capture_duration_seconds = 300  # 5 minutes

# Maximum file size in MB before rotating to a new PCAP file
max_file_size_mb = 100  # 100 MB

# MinIO configuration
[minio]
endpoint = "minio.example.com:9000"
access_key = "YOUR_ACCESS_KEY"
secret_key = "YOUR_SECRET_KEY"
bucket = "pcap-files"
use_ssl = false
