version: '3.8'

services:
  traffic-capture:
    build: .
    container_name: traffic-capture
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config.toml:/app/config.toml:ro
      - pcap_data:/data/pcaps
    env_file:
      - .env

volumes:
  pcap_data:

